const fs = require('fs');
const os = require('os');
const path = require('path');
const { audit } = require('../src/audit');

function mkFixture(name) {
  return fs.mkdtempSync(path.join(os.tmpdir(), `nerviq-jest-${name}-`));
}

function writeJson(dir, file, value) {
  fs.writeFileSync(path.join(dir, file), JSON.stringify(value, null, 2));
}

afterEach(() => {
  // Fixtures are cleaned up in each test's finally block
});

describe('Audit - Empty project', () => {
  test('empty project gets low score', async () => {
    const dir = mkFixture('empty');
    try {
      const result = await audit({ dir, silent: true });
      expect(result.score).toBeLessThan(20);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('empty project has no vacuous passes', async () => {
    const dir = mkFixture('vacuous');
    try {
      const result = await audit({ dir, silent: true });
      const passedKeys = result.results.filter(r => r.passed === true).map(r => r.key);
      expect(passedKeys).not.toContain('hooksAreSpecific');
      expect(passedKeys).not.toContain('commandsUseArguments');
      expect(passedKeys).not.toContain('agentsHaveMaxTurns');
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});

describe('Audit - Stack-aware skipping', () => {
  test('python project skips node_modules check', async () => {
    const dir = mkFixture('python');
    try {
      fs.writeFileSync(path.join(dir, 'requirements.txt'), 'fastapi\npytest\n');
      fs.writeFileSync(path.join(dir, '.gitignore'), '.env\n');
      const result = await audit({ dir, silent: true });
      const check = result.results.find(r => r.key === 'gitIgnoreNodeModules');
      expect(check.passed).toBeNull();
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('non-frontend repos skip frontend design checks', async () => {
    const dir = mkFixture('non-frontend');
    try {
      writeJson(dir, 'package.json', { name: 'cli-tool' });
      const result = await audit({ dir, silent: true });
      const frontendSkill = result.results.find(r => r.key === 'frontendDesignSkill');
      const tailwind = result.results.find(r => r.key === 'tailwindMention');
      expect(frontendSkill.passed).toBeNull();
      expect(tailwind.passed).toBeNull();
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});

describe('Audit - Scoring', () => {
  test('score is between 0 and 100', async () => {
    const dir = mkFixture('score-range');
    try {
      const result = await audit({ dir, silent: true });
      expect(result.score).toBeGreaterThanOrEqual(0);
      expect(result.score).toBeLessThanOrEqual(100);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('project with CLAUDE.md scores higher than empty', async () => {
    const dir = mkFixture('with-claude-md');
    try {
      writeJson(dir, 'package.json', { name: 'test', scripts: { test: 'jest', lint: 'eslint', build: 'tsc' } });
      fs.writeFileSync(path.join(dir, 'CLAUDE.md'), '# Project\n\n## Build\nnpm test\nnpm run lint\nnpm run build\n\n## Style\nUse TypeScript strict mode.\n');
      const result = await audit({ dir, silent: true });
      expect(result.score).toBeGreaterThan(10);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('organic score excludes scaffolded checks', async () => {
    const dir = mkFixture('organic');
    try {
      writeJson(dir, 'package.json', { name: 'test' });
      fs.writeFileSync(path.join(dir, 'CLAUDE.md'), '# Test\nGenerated by nerviq\n\n## Commands\nnpm test\n');
      const result = await audit({ dir, silent: true });
      expect(result.organicScore).toBeLessThanOrEqual(result.score);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('topNextActions has at most 5 items', async () => {
    const dir = mkFixture('top-actions');
    try {
      const result = await audit({ dir, silent: true });
      expect(result.topNextActions.length).toBeLessThanOrEqual(5);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('topNextActions have required fields', async () => {
    const dir = mkFixture('action-fields');
    try {
      const result = await audit({ dir, silent: true });
      for (const action of result.topNextActions) {
        expect(action.key).toBeTruthy();
        expect(action.name).toBeTruthy();
        expect(action.impact).toBeTruthy();
        expect(action.fix).toBeTruthy();
        expect(action.risk).toBeTruthy();
        expect(action.confidence).toBeTruthy();
      }
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});

describe('Audit - JSON output', () => {
  test('json output includes version and timestamp', async () => {
    const dir = mkFixture('json');
    try {
      const consoleSpy = jest.spyOn(console, 'log').mockImplementation();
      const result = await audit({ dir, json: true });
      const output = consoleSpy.mock.calls.map(c => c[0]).join('');
      consoleSpy.mockRestore();
      const parsed = JSON.parse(output);
      expect(parsed.version).toBeTruthy();
      expect(parsed.timestamp).toBeTruthy();
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});

describe('Audit - warnings and deprecations', () => {
  test('large instruction files are reported with byte and line counts', async () => {
    const dir = mkFixture('large-instruction');
    try {
      fs.writeFileSync(path.join(dir, 'CLAUDE.md'), `# Large\n\n${'Use clear verification steps.\n'.repeat(2500)}`);
      const result = await audit({ dir, silent: true });
      expect(result.largeInstructionFiles.length).toBeGreaterThan(0);
      expect(result.largeInstructionFiles[0].byteCount).toBeGreaterThan(50 * 1024);
      expect(result.largeInstructionFiles[0].lineCount).toBeGreaterThan(1000);
      expect(result.results.find(r => r.key === 'largeInstructionFile')).toBeTruthy();
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('instruction files over 1MB are marked skipped', async () => {
    const dir = mkFixture('huge-instruction');
    try {
      fs.writeFileSync(path.join(dir, 'CLAUDE.md'), `# Huge\n\n${'line\n'.repeat(250000)}`);
      const result = await audit({ dir, silent: true });
      expect(result.largeInstructionFiles.some(item => item.skipped)).toBe(true);
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });

  test('deprecated patterns produce deprecation warnings', async () => {
    const dir = mkFixture('deprecated-warning');
    try {
      fs.writeFileSync(path.join(dir, 'CLAUDE.md'), '# Legacy\n\nhuman_prompt: test\nassistant_prompt: test\n');
      const result = await audit({ dir, silent: true });
      expect(result.deprecationWarnings.length).toBeGreaterThan(0);
      expect(result.deprecationWarnings[0]).toHaveProperty('feature');
      expect(result.deprecationWarnings[0]).toHaveProperty('alternative');
    } finally { fs.rmSync(dir, { recursive: true, force: true }); }
  });
});
