const { formatMarkdown } = require('../src/formatters/markdown');

function buildResult() {
  return {
    version: '1.22.0',
    timestamp: '2026-04-14T00:00:00.000Z',
    platform: 'claude',
    platformLabel: 'Claude Code',
    score: 72,
    organicScore: 68,
    passed: 2,
    failed: 2,
    skipped: 1,
    topNextActions: [
      {
        key: 'permissionDeny',
        name: 'Add permission denylist',
        severity: 'critical',
        impact: 'critical',
        file: '.claude/settings.json',
        line: 12,
        fix: 'Add deny entry for shell.exec | run',
      },
      {
        key: 'hooksPresent',
        name: 'Enable pre-tool hooks',
        severity: 'high',
        impact: 'high',
        fix: 'Create .claude/hooks/pre-tool.sh',
      },
    ],
    results: [
      {
        key: 'permissionDeny',
        id: 'PERM-001',
        name: 'Add permission denylist | for shell',
        category: 'permissions',
        rating: 5,
        impact: 'critical',
        passed: false,
        file: '.claude/settings.json',
        line: 12,
        fix: 'Add deny entry',
        sourceUrl: 'https://nerviq.net/c/permissionDeny',
      },
      {
        key: 'hooksPresent',
        id: 'HOOKS-001',
        name: 'Enable pre-tool hooks',
        category: 'hooks',
        rating: 4,
        impact: 'high',
        passed: false,
        fix: 'Create hook file',
      },
      {
        key: 'claudeMdExists',
        id: 'CLAUDEMD-001',
        name: 'CLAUDE.md exists',
        category: 'instruction-surfaces',
        rating: 5,
        impact: 'high',
        passed: true,
      },
    ],
  };
}

describe('formatMarkdown', () => {
  const md = formatMarkdown(buildResult());

  test('contains score heading', () => {
    expect(md).toMatch(/## Score: 72\/100/);
  });

  test('contains task-list checklist for top actions', () => {
    expect(md).toMatch(/- \[ \] \*\*\[CRITICAL\]/);
    expect(md).toMatch(/- \[ \] \*\*\[HIGH\]/);
  });

  test('contains file:line reference', () => {
    expect(md).toMatch(/\.claude\/settings\.json:12/);
  });

  test('includes failed-checks details block with table (CTO-08: includes layer column)', () => {
    expect(md).toMatch(/<details>/);
    expect(md).toMatch(/\| key \| name \| category \| layer \| rating \| file \| line \|/);
  });

  test('CTO-08: next-action lines include a layer suffix when layer is present', () => {
    const result = buildResult();
    result.topNextActions[0].layer = 'governance';
    const out = formatMarkdown(result);
    expect(out).toMatch(/_layer: governance_/);
  });

  test('escapes pipe characters inside table cells', () => {
    // The check name contains "|" which must be escaped to "\|" in the table row.
    expect(md).toMatch(/Add permission denylist \\\| for shell/);
  });

  test('has Nerviq footer with version and timestamp', () => {
    expect(md).toMatch(/Generated by \[Nerviq\]\(https:\/\/nerviq\.net\) v1\.22\.0/);
    expect(md).toMatch(/2026-04-14T00:00:00\.000Z/);
  });

  test('does not emit raw stripped HTML', () => {
    // GitHub strips <script>, <style>, <iframe>. We should never emit these.
    expect(md).not.toMatch(/<script|<style|<iframe/i);
  });

  test('renders snippet as fenced code block when present (CTO-04)', () => {
    const result = buildResult();
    result.topNextActions[0].snippet = 'line-a\nline-b\nline-c';
    const out = formatMarkdown(result);
    expect(out).toMatch(/```\s*\n\s*line-a/);
    expect(out).toContain('line-b');
  });

  test('renders projected score delta when present (CTO-05)', () => {
    const result = buildResult();
    result.topNextActions[0].projectedScoreDelta = 7;
    result.topNextActions[0].projectedScoreAfter = 79;
    const out = formatMarkdown(result);
    expect(out).toMatch(/\(\+7 pts → 79\/100\)/);
  });

  test('renders shallow-risk hints in a dedicated section (CTO-06)', () => {
    const result = buildResult();
    result.shallowRiskHints = [
      {
        key: 'agent-config-missing-file',
        name: 'Agent config references missing file',
        severity: 'high',
        layer: 'shallow-risk',
        file: 'CLAUDE.md',
        line: 3,
        fix: 'Create docs/SECURITY.md',
      },
    ];
    const out = formatMarkdown(result);
    expect(out).toMatch(/### Shallow Risk \(experimental, opt-in\)/);
    expect(out).toMatch(/Agent config references missing file/);
    expect(out).toMatch(/> Shallow Risk mode \(experimental, opt-in\)/);
  });

  test('omits snippet block gracefully when absent', () => {
    const out = formatMarkdown(buildResult());
    // No snippet in fixture; ensure we didn't emit a stray empty fenced block.
    expect(out).not.toMatch(/```\n\s*```/);
  });
});
