/**
 * Markdown Formatter
 *
 * Converts a nerviq audit result into GitHub-flavoured markdown suitable
 * for posting as a PR comment. Structure:
 *
 *   - Header with score badge and pass/fail/skip counts
 *   - Top 5 topNextActions as a GitHub task-list checklist
 *   - Collapsible <details> block with the full failed-checks table
 *   - Footer with Nerviq link, version, timestamp
 *
 * Output is plain GitHub-flavoured markdown. The only HTML used is
 * <details>/<summary>, which GitHub renders natively.
 */

'use strict';

const { version: nerviqVersion } = require('../../package.json');

function escapeCell(value) {
  if (value === null || value === undefined) return '';
  return String(value)
    .replace(/\r?\n/g, ' ')
    .replace(/\|/g, '\\|');
}

function escapeInline(value) {
  if (value === null || value === undefined) return '';
  return String(value).replace(/\r?\n/g, ' ');
}

function scoreBadge(score) {
  const s = Number.isFinite(score) ? Math.round(score) : 0;
  let color;
  if (s >= 80) color = 'brightgreen';
  else if (s >= 60) color = 'yellow';
  else color = 'red';
  return `![score](https://img.shields.io/badge/nerviq_score-${s}%2F100-${color})`;
}

function severityFor(item) {
  return item.severity || item.impact || 'medium';
}

function formatMarkdown(auditResult, options = {}) {
  const platformLabel = auditResult.platformLabel || auditResult.platform || 'claude';
  const score = auditResult.score ?? 0;
  const passed = auditResult.passed ?? 0;
  const failed = auditResult.failed ?? 0;
  const skipped = auditResult.skipped ?? 0;
  const version = auditResult.version || nerviqVersion;
  const timestamp = auditResult.timestamp || new Date().toISOString();

  const lines = [];

  lines.push(`## Score: ${score}/100 ${scoreBadge(score)}`);
  lines.push('');
  lines.push(`**Platform:** ${platformLabel}  `);
  lines.push(`**Checks:** ${passed} passed, ${failed} failed, ${skipped} skipped`);
  lines.push('');

  const top = Array.isArray(auditResult.topNextActions)
    ? auditResult.topNextActions.slice(0, 5)
    : [];

  if (top.length > 0) {
    lines.push('### Top next actions');
    lines.push('');
    for (const item of top) {
      const sev = severityFor(item).toString().toUpperCase();
      const title = escapeInline(item.name || item.title || item.key);
      const key = escapeInline(item.key || item.id || '');
      let loc = '';
      if (item.file) {
        loc = ` — \`${escapeInline(item.file)}${item.line ? ':' + item.line : ''}\``;
      }
      let delta = '';
      if (Number.isFinite(item.projectedScoreDelta) && item.projectedScoreDelta > 0) {
        delta = ` (+${item.projectedScoreDelta} pts → ${item.projectedScoreAfter}/100)`;
      }
      // CTO-08: include scope layer as a small suffix after the key so
      // evaluators see which layer each next-action belongs to.
      const layerSuffix = item.layer ? ` · _layer: ${escapeInline(item.layer)}_` : '';
      lines.push(`- [ ] **[${sev}] ${title}** (\`${key}\`)${loc}${delta}${layerSuffix}`);
      const hint = item.fix || item.hint || '';
      if (hint) {
        lines.push(`  - ${escapeInline(hint)}`);
      }
      if (item.snippet) {
        lines.push('');
        lines.push('  ```');
        for (const snipLine of String(item.snippet).split(/\r?\n/)) {
          lines.push(`  ${snipLine}`);
        }
        lines.push('  ```');
      }
    }
    lines.push('');
  }

  const failedResults = Array.isArray(auditResult.results)
    ? auditResult.results.filter((r) => r.passed === false)
    : [];

  if (failedResults.length > 0) {
    lines.push('<details>');
    lines.push(`<summary>All failed checks (${failedResults.length})</summary>`);
    lines.push('');
    // CTO-08: add layer column between category and rating.
    lines.push('| key | name | category | layer | rating | file | line |');
    lines.push('| --- | --- | --- | --- | --- | --- | --- |');
    for (const r of failedResults) {
      const row = [
        escapeCell(r.key),
        escapeCell(r.name),
        escapeCell(r.category),
        escapeCell(r.layer || ''),
        escapeCell(r.rating ?? ''),
        escapeCell(r.file || ''),
        escapeCell(r.line || ''),
      ];
      lines.push(`| ${row.join(' | ')} |`);
    }
    lines.push('');
    lines.push('</details>');
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`Generated by [Nerviq](https://nerviq.net) v${version} · ${timestamp}`);

  return lines.join('\n');
}

module.exports = { formatMarkdown };
